name: build and deploy

on:
  push:
    branches: [ master ]
    
jobs:  
 
  clean:
    name: Clean
    runs-on: ubuntu-latest
    steps:
    - name: Clean lagacy code
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: rm -rf /home/wwwroot/vr.iecho.cc/*
  
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
        
    - name: deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        source: "dist/"
        target: "/home/wwwroot/vr.iecho.cc/" 
        strip_components: 1
